UPDATE `bbi_bg_web_db`.`companies` SET `id`='42' WHERE `id`='41';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='43' WHERE `id`='42';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='44' WHERE `id`='43';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='45' WHERE `id`='44';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='46' WHERE `id`='45';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='47' WHERE `id`='46';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='48' WHERE `id`='47';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='49' WHERE `id`='48';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='50' WHERE `id`='49';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='51' WHERE `id`='50';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='52' WHERE `id`='51';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='57' WHERE `id`='52';
UPDATE `bbi_bg_web_db`.`companies` SET `id`='41' WHERE `id`='55';
INSERT INTO `bbi_bg_web_db`.`companies` (`id`, `name`, `about`, `address`, `phone`, `link`, `bbi_id`, `opening_time`, `category_id`, `province_id`, `created_at`, `updated_at`) VALUES ('55', 'HỘ KINH DOANH NGỤY NGỌC ĐẠT', 'Cây cảnh tích điểm từ 50% đến 100%', 'SN 18, Tổ dân phố Hà Vị 2, Phường Thọ Xương, Thành phố Bắc Giang, Tỉnh Bắc Giang', '0982.949.757', '', 'NGOCDAT376', '08:30 - 21:30 (Thứ 2 - Chủ nhật)', '4', '6', 'now()', 'now()');
INSERT INTO `bbi_bg_web_db`.`companies` (`id`, `name`, `about`, `address`, `phone`, `link`, `bbi_id`, `opening_time`, `category_id`, `province_id`, `created_at`, `updated_at`) VALUES ('56', 'HỘ KINH DOANH NGUYỄN THỊ YÊN', 'Tiêu dùng tích điểm lên đến 100%', 'Thôn Hà Mỹ,, Xã Chu Điện, Huyện Lục Nam, Tỉnh Bắc Giang', '0382.837.288', '', 'YEN177', '08:30 - 22:00 (Thứ 2 - Chủ nhật)', '5', '8', 'now()', 'now()');
